#ifndef GLOBALS_H
#define GLOBALS_H

#define MOVE "MOVE"
#define READ "READ"
#define SETUP "SETUP"

#define SERVO_MAX_ANGLE 180
#define SERVO_MIN_ANGLE 0

#define SERVO_1 "SERVO1"
#define SERVO_2 "SERVO2"
#define SERVO_3 "SERVO3"
#define SERVO_4 "SERVO4"
#define SERVO_5 "SERVO5"
#define SERVO_6 "SERVO6"
#define OFFSET_1 "OFFSET1"
#define OFFSET_2 "OFFSET2"
#define OFFSET_3 "OFFSET3"
#define OFFSET_4 "OFFSET4"
#define OFFSET_5 "OFFSET5"
#define OFFSET_6 "OFFSET6"

#define SERVO_ANGLES "ANGLES"
#define SERVO_ANGLES_WITH_OFFSET "ANGLES_WITH_OFFSET"
#define SERVO_OFFSETS "OFFSETS"
#define SERVO_SPEED "SPEED"

#endif // GLOBALS_H